Add Refresh Terminologies Cache Functionality
G-Node/odml-ui pull request #178
Opened 2020-06-02 10:39 UTC by fschrader1992

This PR:

- Adds a function calling odml terminologies refresh to update cache files. Closes #118

2020-06-02 11:07 UTC, fschrader1992 commented
Checks for Code Quality:
- [x] Pylint
- [x] Rebase onto GNODE Master
- [x] Test with Python3.8

2020-06-02 12:14 UTC, mpsonntag requested changes
The current implementation locks the editor until the refresh is done basically freezing the application for the user without feedback.

It would be better to run the actual refresh in the background.

2020-06-03 07:53 UTC, mpsonntag requested changes

2020-06-03 07:53 UTC, mpsonntag commented on odmlui/editor.py
> +            thread = threading.Thread(target=lambda rep_url: terminology.refresh, args=(url,))
This does not work as expected. Please test properly before pushing a commit.

2020-06-19 12:56 UTC, fschrader1992 commented
Checks for Code Quality:
- [x] Pylint
- [x] Rebase onto GNODE Master
- [x] Test with Python3.8

2020-06-19 13:00 UTC, merged