General improvements and bug fixes
G-Node/odml-ui pull request #23
Opened 2017-07-27 15:22 UTC by digaru19

2017-07-28 10:10 UTC, achilleas-k commented
Is there a way to toggle the `DEBUG` flag externally or can it only be done in code for now?

2017-07-28 11:15 UTC, jgrewe commented
maybe use argparse package to define the user interface

2017-07-28 11:22 UTC, achilleas-k commented on odmlui/dnd/tree.py
> +        return (self.action == gtk.gdk.ACTION_COPY) != 0
Clean up `!= 0`

2017-07-28 11:23 UTC, achilleas-k requested changes
Some comments:
- Clean up the two `!= 0` for the action comparisons.
- Add a command line debug flag that sets `DEBUG = True`.
- Print errors to `stderr` and debug output to `stdout`.

2017-07-28 11:23 UTC, achilleas-k commented on odmlui/dnd/tree.py
> +        return (self.action == gtk.gdk.ACTION_LINK) != 0
Clean up `!= 0`

2017-08-07 11:34 UTC, achilleas-k approved these changes

2017-08-07 11:35 UTC, merged